# Generated by Django 2.1 on 2018-08-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.Fertilizer')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrients.Nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='nutrients',
            field=models.ManyToManyField(through='fertilizers.NutrientContent', to='nutrients.Nutrient'),
        ),
    ]
