# Generated by Django 2.1 on 2018-08-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0002_auto_20180815_0917'),
        ('fertilizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutrientcontent',
            unique_together={('nutrient', 'fertilizer')},
        ),
    ]
