# Generated by Django 2.1 on 2018-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
